version: "3.3"
services:
  app:
    build:
      args:
        user: policiadev
        uid: 1000
      context: ./
      dockerfile: ./docker/Dockerfile
    image: php81
    extra_hosts:
        - host.docker.internal:host-gateway
    container_name: ${APP_NAME}-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/docker-compose/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - dev

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - dev
    links:
      - app


  # db:
  #   image: postgres:13-alpine
  #   restart: unless-stopped
  #   container_name: ${APP_NAME:-postgres}-db
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-123456789}
  #   ports:
  #     - "${DB_PORT:-5432}:${DB_PORT:-5432}"
  #   volumes:
  #     - /home/${USUARIO:-dime}/postgresdb:/var/lib/postgresql/data
  #   networks:
  #     - dev
  db:
    container_name: especializati-mysql
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
    volumes:
        - /home/policiadev/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
    networks:
        - dev


networks:
  dev:
    driver: bridge
